services:
  nest-api:
    container_name: nest-api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://prisma:prisma@postgres:5432/shopperdb?schema=public
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  front:
    build:
      context: ./front
    ports:
      - "80:80"
    environment:
      - REACT_APP_GOOGLE_API_KEY=your-google-api-key
      - REACT_APP_API_ROUTE=http://localhost:3000
    volumes:
      - ./front:/usr/src/app
    networks:
      - shopper-network
    command: >
      sh -c "echo -e 'REACT_APP_GOOGLE_API_KEY=your-google-api-key\nREACT_APP_API_ROUTE=http://localhost:3000' > /usr/src/app/.env && serve -s build"

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: shopperdb
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "prisma"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

networks:
  shopper-network:
    driver: bridge

volumes:
  postgres:
    name: nest-db
